spring.application.name=PPM_project
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/PPM?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
# === JPA / HIBERNATE ===
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
